FILES = Main.cpp

DIRECTORIES = -I../CabbageCore/

OPENGL = -DGL_GLEXT_PROTOTYPES -lGL -lGLU -lSDL
CABBAGE = 

CabbageColliderDemo: $(FILES)
	g++ -o $@ $(FILES) $(DIRECTORIES) $(OPENGL) $(CABBAGE)

